name: PWA CI/CD Workflow

on:
  push:
    branches:
      - development         # Para pruebas internas
      - feature/*           # Ramas de características específicas por desarrollador
      - main                # Para despliegue en producción
      - release/*           # Ramas de release para producción
  pull_request:
    branches:
      - development
      - main
      - release/*
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Comprobación del Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuración del Entorno de Node.js
      - name: Setup Node.js environment  # Instalación de Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Versión específica de Node.js
          
      # Restauración de caché para dependencias de Node.js (npm/yarn)
      - name: Restore npm cache  # Optimiza el caché de dependencias
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Instalación de dependencias
      - name: Install Dependencies  # Instala las dependencias del proyecto
        run: npm install

      # Configuración de variables de entorno
      - name: Set environment variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "STAGING_TOKEN=${{ secrets.STAGING_TOKEN }}" >> $GITHUB_ENV

      # Mensaje para confirmar el entorno
      - name: Mensaje
        run: echo "Hola mundo!!!"

      # Crear un archivo
      - name: Touch file # Crea el archivo
        run: |
          touch hola.txt
          ls -al

      # Agregar texto al archivo
      - name: Set text # Agrega texto al archivo
        run: |
          echo "Hola mundo" >> hola.txt
          ls -al

      # Leer el archivo
      - name: Read file # Lee el archivo
        run: |
          cat hola.txt
          ls -al

      # Ejecuta pruebas unitarias
      #- name: Run Tests
      #  run: npm test

  deploy:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Comprobación del Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuración del Entorno de Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Instalación de dependencias
      - name: Install Dependencies
        run: npm install

      # Despliegue a Producción
      - name: Deploy to Production
        run: |
          echo "Deploying application..."
          # Aquí agregarías tu lógica de despliegue (ej: script de despliegue)
