name: PWA CI/CD Workflow

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configuración de Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Cache de dependencias
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-cache-${{ runner.os }}

    - name: Instalación de dependencias
      run: npm install

    - name: Compilación del proyecto
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: install-and-build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Despliegue en Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: npx vercel --prod --token $VERCEL_TOKEN
